shop:
  - id: 1
    name: Связной
  - id: 2
    name: DNS
categories:
  - id: 224
    name: Смартфоны
  - id: 15
    name: Аксессуары
  - id: 1
    name: Flash-накопители
  - id: 5
    name: Телевизоры
  - id: 7
    name: Мониторы
  - id: 10
    name: Инструменты
  - id: 14
    name: Офисная мебель
  - id: 18
    name: Садовая техника

goods:
  - id: 4216292
    shop: 
      id: 1
    category: 224
    model: apple/iphone/xs-max
    name: Смартфон Apple iPhone XS Max 512GB (золотистый)
    price: 110000
    price_rrc: 116990
    quantity: 14
    parameters:
      "Диагональ (дюйм)": 6.5
      "Разрешение (пикс)": 2688x1242
      "Встроенная память (Гб)": 512
      "Цвет": золотистый
  - id: 4216313
    shop:
      id: 2
    category: 224
    model: apple/iphone/xr
    name: Смартфон Apple iPhone XR 256GB (красный)
    price: 65000
    price_rrc: 69990
    quantity: 9
    parameters:
      "Диагональ (дюйм)": 6.1
      "Разрешение (пикс)": 1792x828
      "Встроенная память (Гб)": 256
      "Цвет": красный
  - id: 4216226
    shop: 
      id: 1
    category: 224
    model: apple/iphone/xr
    name: Смартфон Apple iPhone XR 256GB (черный)
    price: 65000
    price_rrc: 69990
    quantity: 5
    parameters:
      "Диагональ (дюйм)": 6.1
      "Разрешение (пикс)": 1792x828
      "Встроенная память (Гб)": 256
      "Цвет": черный
  - id: 46234243
    shop: 
      id: 2
    category: 224
    model: apple/iphone/xr
    name: Смартфон Apple iPhone XR 256GB (черный)
    price: 64999
    price_rrc: 69990
    quantity: 5
    parameters:
      "Диагональ (дюйм)": 6.1
      "Разрешение (пикс)": 1792x828
      "Встроенная память (Гб)": 256
      "Цвет": черный
  - id: 4672670
    shop: 
      id: 2
    category: 224
    model: apple/iphone/xr
    name: Смартфон Apple iPhone XR 128GB (синий)
    price: 60000
    price_rrc: 64990
    quantity: 7
    parameters:
      "Диагональ (дюйм)": 6.1
      "Разрешение (пикс)": 1792x828
      "Встроенная память (Гб)": 256
      "Цвет": синий
  - id: 1234567
    shop: 
      id: 1
    category: 15
    model: samsung/galaxy-s20
    name: Smartphone Samsung Galaxy S20 128GB (black)
    price: 80000
    price_rrc: 84990
    quantity: 5
    parameters:
      "Screen Size (inches)": 6.2
      "Resolution (pixels)": 3200x1440
      "Internal Memory (GB)": 128
      "Color": black
  - id: 1234568
    shop: 
      id: 2
    category: 15
    model: samsung/galaxy-note20
    name: Smartphone Samsung Galaxy Note20 256GB (mystic bronze)
    price: 95000
    price_rrc: 99990
    quantity: 3
    parameters:
      "Screen Size (inches)": 6.7
      "Resolution (pixels)": 2400x1080
      "Internal Memory (GB)": 256
      "Color": mystic bronze
  - id: 1235464569
    shop: 
      id: 1
    category: 1
    model: sandisk/ultra-flair-64gb
    name: USB Flash Drive SanDisk Ultra Flair 64GB (silver)
    price: 1500
    price_rrc: 1990
    quantity: 10
    parameters:
      "Capacity (GB)": 64
      "Color": silver
  - id: 1235434570
    shop: 
      id: 1
    category: 1
    model: kingston/datatraveler-32gb
    name: USB Flash Drive Kingston DataTraveler 32GB (red)
    price: 1000
    price_rrc: 1290
    quantity: 8
    parameters:
      "Capacity (GB)": 32
      "Color": red
  - id: 123544571
    shop: 
      id: 2
    category: 224
    model: xiaomi/mi-10t-pro
    name: Smartphone Xiaomi Mi 10T Pro 256GB (cosmic black)
    price: 70000
    price_rrc: 74990
    quantity: 6
    parameters:
      "Screen Size (inches)": 6.67
      "Resolution (pixels)": 2400x1080
      "Internal Memory (GB)": 256
      "Color": cosmic black
  - id: 1234572
    shop: 
      id: 1
    category: 5
    model: samsung/qled-q90r
    name: Samsung QLED Q90R 65" 4K UHD Smart TV
    price: 2500
    price_rrc: 2999
    quantity: 4
    parameters:
      "Screen Size (inches)": 65
      "Resolution (pixels)": 3840x2160
      "Smart TV": true
  - id: 123476573
    shop: 
      id: 2
    category: 5
    model: lg/oled-cx
    name: LG OLED CX 55" 4K UHD Smart TV
    price: 1800
    price_rrc: 1999
    quantity: 7
    parameters:
      "Screen Size (inches)": 55
      "Resolution (pixels)": 3840x2160
      "Smart TV": true
  - id: 1234453574
    shop: 
      id: 1
    category: 5
    model: sony/bravia-x900h
    name: Sony Bravia X900H 75" 4K UHD Smart TV
    price: 3000
    price_rrc: 3499
    quantity: 3
    parameters:
      "Screen Size (inches)": 75
      "Resolution (pixels)": 3840x2160
      "Smart TV": true
  - id: 123234575
    shop: 
      id: 1
    category: 5
    model: tcl/6-series
    name: TCL 6-Series 55" 4K UHD Smart TV
    price: 700
    price_rrc: 799
    quantity: 10
    parameters:
      "Screen Size (inches)": 55
      "Resolution (pixels)": 3840x2160
      "Smart TV": true
  - id: 123424576
    shop: 
      id: 2
    category: 5
    model: vizio/p-series-quantum
    name: Vizio P-Series Quantum 65" 4K UHD Smart TV
    price: 1200
    price_rrc: 1299
    quantity: 5
    parameters:
      "Screen Size (inches)": 65
      "Resolution (pixels)": 3840x2160
      "Smart TV": true
  - id: 42265236
    shop: 
      id: 1
    category: 7
    model: ARDOR GAMING PORTAL AF24H1
    name: Монитор ARDOR GAMING PORTAL AF24H1 (черный)
    price: 13999
    price_rrc: 15000
    quantity: 59
    parameters:
      "Диагональ (дюйм)": 23.8
      "Разрешение (пикс)": 1920x1080 (FullHD)
      "Цвет": черный
  - id: 223525414
    shop: 
      id: 2
    category: 10
    model: Zitrek Green 12 063-4071
    name: Дрель-шуруповерт Zitrek Green 12 063-4071
    price: 1099
    price_rrc: 1200
    quantity: 190
    parameters:
      "Тип крепления патрона": 3.8
      "Максимальное число оборотов холостого хода (1-я скорость) ": 600 об/мин
      "Жесткий крутящий момент": 32 
      "Режим сверления": есть
  - id: 223623
    shop: 
      id: 2
    category: 18
    model: FinePower PLM130-41
    name: Газонокосилка бензиновая FinePower PLM130-41
    price: 13999
    price_rrc: 14000
    quantity: 6
    parameters:
      "Мощность": 2.7
      "Мульчирование": нет
      "Ширина скашивания": 410 мм
      "Травосборник": есть
  - id: 23542562
    shop: 
      id: 2
    category: 14
    model: DEXP Gritt 20W
    name: Кресло игровое DEXP Gritt 20W красный
    price: 5999
    price_rrc: 6500
    quantity: 14
    parameters:
      "Материал обивки": ткань, экокожа
      "Подголовник": нет
      "Вес": 13 кг
      "Ограничение по весу": 120 кг